services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ollama list || exit 1
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s

  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
    ports:
      - 80:8080
    volumes:
      - open_webui_data:/app/backend/data
    extra_hosts:
      - host.docker.internal:host-gateway

  ollama-models-pull:
    image: curlimages/curl:latest
    container_name: ollama-models-pull
    command: >-
      http://ollama:11434/api/pull -d '{"name": "mistral"}'
    depends_on:
      ollama:
        condition: service_healthy


  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      VECTOR_STORE_TYPE: pgVector

volumes:
  ollama_data:
  open_webui_data:
