server:
  port: 8082

spring:
  application:
    name: spring-ai-rag-demo
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      resolve-lazily: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/documentgpt}
    username: ${SPRING_DATASOURCE_USERNAME:documentgpt}
    password: ${SPRING_DATASOURCE_PASSWORD:documentgptpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  ai:
    vectorstore:
      pgvector:
        initialize-schema: true
        remove-existing-vector-store-table: true
        table-name: documents_vector
    openai:
      api-key: test
      embedding:
        enabled: false
    ollama:
      embedding:
        enabled: false