server:
  port: 8082

spring:
  application:
    name: spring-ai-rag-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/document
    username: document_poc
    password: document_password
    jpa:
      hibernate:
        ddl-auto: update
    servlet:
      multipart:
        max-file-size: 10MB
    ai:
      ollama:
        chat:
          options:
            model: mistral
        embedding:
          enabled: true
          options:
            model: nomic-embed-text
        vectorstore:
          pgvector:
            initialize-schema: true
            remove-existing-vector-store-table: true
            table-name: documents
  docker:
    compose:
      file: ./docker-compose.yml
      lifecycle-management: none
