spring:
  config:
    activate:
      on-profile: dev
  ai:
    ollama:
      embedding:
        enabled: true
        options:
          model: ${EMBEDDING_MODEL:nomic-embed-text}
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        options:
          model: ${CHAT_MODEL:mistral}
  docker:
    compose:
      file: ./compose-ollama.yml
      lifecycle-management: none
