server:
  port: 8082

spring:
  application:
    name: spring-ai-rag-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  ai:
    ollama:
      chat:
        options:
          model: mistral
      embedding:
        options:
          model: mistral
        model: mistral
    vectorstore:
      pgvector:
        index-type: none
        distance-type: cosine_distance
        dimensions: 4096
        initialize-schema: true
  docker:
    compose:
      file: ./docker-compose.yml
      lifecycle-management: none