spring:
  application:
    name: spring-ai-rag-demo
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:vectordb}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  ai:
    ollama:
      base-url: http://localhost:11434/
      chat:
        options:
          temperature: 0.7
          model: phi3