server:
  port: 8082

spring:
  application:
    name: spring-ai-rag-demo
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      resolve-lazily: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/documentgpt}
    username: ${SPRING_DATASOURCE_USERNAME:documentgpt}
    password: ${SPRING_DATASOURCE_PASSWORD:documentgptpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  ai:
    ollama:
      embedding:
        enabled: true
        options:
          model: ${EMBEDDING_MODEL:nomic-embed-text}
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        options:
          model: ${CHAT_MODEL:mistral}
    vectorstore:
      pgvector:
        initialize-schema: true
        remove-existing-vector-store-table: true
        table-name: documents_vector

  docker:
    compose:
      file: ./docker-compose.yml
      lifecycle-management: none
