spring:
  config:
    activate:
      on-profile: prod
  ai:
    openai:
      embedding:
        enabled: true
      api-key: ${REMOTE_LLM_KEY} # informed by environment variable
      base-url: ${REMOTE_LLM_BASE_URL:https://api.openai.com}
      chat:
        options:
          model: ${CHAT_MODEL:gpt-4o-mini}

  docker:
    compose:
      file: ./compose.yml
      lifecycle-management: none